cursos/urls.py
from django.urls import path

from cursos import views

app_name = "course"
urlpatterns = [
    path("courses/", views.CourseListView.as_view(), name="course-list"),
    path("course/add/", views.CourseCreateView.as_view(), name="course-add"),
    path("course/<int:pk>/detail/", views.CourseDetailView.as_view(), name="course-detail"),
    path("course/<int:pk>/update/", views.CourseUpdateView.as_view(), name="course-update"),
    path("course/<int:pk>/delete/", views.CourseDeleteView.as_view(), name="course-delete"),
    path("comment/<int:pk>/add/", views.CommentCreateView.as_view(), name="comment-create"),
    path("comment/<int:pk>/delete/", views.CommentDeleteView.as_view(), name="comment-delete"),

    path("homeworks", views.HomeworkListView.as_view(), name="homework-list"),
    path("homework/add/", views.HomeworkCreateView.as_view(), name="homework-add"),
    path("homework/<int:pk>/detail/", views.HomeworkDetailView.as_view(), name="homework-detail"),
    path("homework/<int:pk>/update/", views.HomeworkUpdateView.as_view(), name="homework-update"),
    path("homework/<int:pk>/delete/", views.HomeworkDeleteView.as_view(), name="homework-delete"),
]

cursos/templates/comentario_crear_eliminar.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Comentario delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Eliminar Comentario</h1>
                    <span class="subheading">Creado por: {{ comment.owner.first_name }} {{ comment.owner.last_name }}</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el siguiente Comentario?</h1>
<p>{{ comment.text }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'course:course-detail' comment.course.id %}" >Cancelar</a>
</form>

{% endblock %}

cursos/templates/curso_confirmar_eliminar.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Course delete
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ course.name }}</h1>
                    <span class="subheading">Eliminar Curso</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>Estás seguro de eliminar el Curso: {{ course.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'course:course-list' %}" >Cancelar</a>
</form>

{% endblock %}

cursos/templates/curso_forma.html
{% extends "home/index.html" %}
{% load static %}

<!-- ckeditor-->
{% block extrahead %}
<script>window.CKEDITOR_BASEPATH = '/static/ckeditor/ckeditor/';</script>
{{ block.super }}
{% endblock %}
<!-- ckeditor-->

{% block my_blog_title %}
Cursos Creados-Actualizados
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h2>Formulario para guardar/editar curso</h2>
                    <span class="subheading">My blog_cocina</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}

{% block my_blog_content %}
    <div>
        <form action="" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }} <!-- ckeditor-->
            {{ form.as_p }}
            <input type="submit" class="btn btn-primary" value="Guardar curso" />
        </form>
    </div>
    <!-- Divider-->
    <hr class="my-4" />
{% endblock %}

cursos/templates/curso_listado.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Lista de Cursos
{% endblock %}

{% block blog_cocina %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>Listado de cursos</h1>
                    <span class="subheading">My blog CoderHouse</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'course:course-add' %}">Crear nuevo Curso</a>
    </div>
</header>
{% endblock %}


{% block blog_cocina %}
    {% for course in course_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'course:course-detail' course.id %}">
                <h2 class="post-title">Este curso es de {{ course.name }}</h2>
                <h3 class="post-subtitle">Código: {{ course.code }}</h3>
            </a>
            <p class="post-meta">
                Creado por
                <span style="color: #ceb008;" href="">{{ course.owner.username }}</span>
                ( {{ course.created_at }} )
            </p>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}

cursos/templates/cursos_info.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Informacion de cursos
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/about-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ course.name }}</h1>
                    <span class="subheading">Informacion del curso</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'course:course-add' %}">Crear nuevo curso</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Código: {{ course.code }}</h3>
    <p class="post-meta">
        Creado por
        <span style="color: #2dcdec;" href="">{{ course.owner.username }}</span>
        ( {{ course.created_at }} )
        <br>
        Última fecha de actualización ( {{ course.updated_at }} )
    </p>

    <!-- Image -->
    {% if course.image %}
        <div style="text-align: center;">
            <img height="250px" src="{{ course.image.url }}">
        </div>
    {% endif %}

    <!-- Description -->
    <p class="card-text ">{{ course.description|safe }}</p> <!-- ckeditor-->

    <!-- Update-Delete link only for the owner -->
    {% if user == course.owner or user.is_superuser %}
        <p style="text-align: center">
            <a href="{% url 'course:course-update' course.id %}">
                <i class="fa fa-pencil" style="color: #056805;"></i> Editar Curso
            </a>
            &ensp; | &ensp;
            <a href="{% url 'course:course-delete' course.id %}">
                <i class="fa fa-trash" style="color: #881a1a;"></i> Eliminar Curso
            </a>
        </p>
    {% endif %}
    
    <!-- Divider-->
    <hr class="my-4" />

    <!-- Comment creation -->
    <form method="POST" action="{% url 'course:comment-create' course.id %}">
        {% csrf_token %}
        {{ comment_form }}
    <input type="submit" value="Publicar comentario">
    </form>
    {% if not comments %}
        <p></p>
    {% endif %}

    <!-- Comments list -->
    {% for comment in comments %}
        <p> {{ comment.text }}
            ({{ comment.owner.username }} | {{ comment.updated_at }})
            {% if user == comment.owner or user.is_superuser %}
            <a href="{% url 'course:comment-delete' comment.id %}"><i class="fa fa-trash" style="color: #881a1a;"></i></a>
            {% endif %}
        </p>
    {% endfor %}
</div>
{% endblock %}

cursos/templates/ejercicios_eliminar.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Borrar Ejercicio
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ homework.name }}</h1>
                    <span class="subheading">Eliminar Ejercicio</span>
                </div>
            </div>
        </div>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}

<h1>¿Quieres eliminar el Ejercicio: {{ homework.name }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input class="btn btn-danger" type="submit" value="Si, eliminar.">
    <a class="btn btn-primary" href="{% url 'course:homework-list' %}" >Cancelar</a>
</form>

{% endblock %}

cursos/templates/ejercicios_info.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Trabajos
{% endblock %}

{% block my_blog_header %}
<header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
    <div class="container position-relative px-4 px-lg-5">
        <div class="row gx-4 gx-lg-5 justify-content-center">
            <div class="col-md-15 col-lg-16 col-xl-14">
                <div class="site-heading">
                    <h1>{{ homework.name }}</h1>
                    <span class="subheading">Detalles de la entrega</span>
                </div>
            </div>
        </div>
        <a class="button_custom" href="{% url 'course:homework-add' %}">Crear nuevo Entregable</a>
    </div>
</header>
{% endblock %}


{% block my_blog_content %}
<!-- Post preview-->
<div class="post-preview">
    <h3 class="post-subtitle">Vencimiento de la entrega {{ homework.due_date }}</h3>
    <h5>
        Entregado:
        {% if homework.is_delivered %}
            Si
        {% else %}
            No
        {% endif%}
    </h5>
    <p style="text-align: center">
        <a href="{% url 'course:homework-update' homework.id %}">
            <i class="fa fa-pencil" style="color: #37ee1f;"></i> Editar
        </a>
        &ensp; | &ensp;
        <a href="{% url 'course:homework-delete' homework.id %}">
            <i class="fa fa-trash" style="color: #ca1d1d;"></i> Eliminar 
        </a>
    </p>
</div>
{% endblock %}

cursos/templates/ejercicios_lista.html
{% extends "home/index.html" %}
{% load static %}

{% block my_blog_title %}
Ejercicios
{% endblock %}

{% block my_blog_header %}
    <header class="masthead" style="background-image: url('/static/home/assets/img/post-bg.jpg')">
        <div class="container position-relative px-4 px-lg-5">
            <div class="row gx-4 gx-lg-5 justify-content-center">
                <div class="col-md-15 col-lg-16 col-xl-14">
                    <div class="site-heading">
                        <h1>Lista de Ejercicios</h1>
                        
                    </div>
                </div>
            </div>
            <a class="button_custom" href="{% url 'course:homework-add' %}">Crear Ejercicio</a>
    </div>
    </header>
{% endblock %}

{% block my_blog_content %}
    {% for homework in homework_list %}
        <!-- Post preview-->
        <div class="post-preview">
            <a href="{% url 'course:homework-detail' homework.id %}">
                <h2 class="post-title">Este es el entregable: {{ homework.name }}</h2>
                <h3 class="post-subtitle">Vencimiento de la entrega: {{ homework.due_date }}</h3>
            </a>
        </div>
        <!-- Divider-->
        <hr class="my-4" />
    {% endfor %}
{% endblock %}